[package]
name = "Rust_Security_Camera"
version = "0.1.0"
edition = "2024"

[dependencies]
opencv = "0.88"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
anyhow = "1.0"